// 设置个人信息
const SET_USER_DATA = 'SET_USER_DATA'
const SET_ORDER_CODE = 'SET_ORDER_CODE'
const SET_EVALUATE_DATA = 'SET_EVALUATE_DATA'
const SET_EVALUATE_DETAIL_DATA = 'SET_EVALUATE_DETAIL_DATA'
export default {
  SET_USER_DATA,
  SET_ORDER_CODE,
  SET_EVALUATE_DATA,
  SET_EVALUATE_DETAIL_DATA
}
